# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AdamSellin.EasyTab
PackageVersion: 0.1.11
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: easytab-x86_64-pc-windows-msvc\easytab.exe
  PortableCommandAlias: easytab
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AdamSellin/EasyTab/releases/download/v0.1.11/easytab-x86_64-pc-windows-msvc.zip
  InstallerSha256: D335D6BF8059A7F2EA5FBDA62AED7C2EE307700EC682C1E35674E93D7025FABF
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-07
